### ISSUE TITLE
Design the Footer Page

### ISSUE THREAD

**Issue by Abhay-hack** [RCCTechzClub/TechzRevamp#10]
Redesign the footer page. Adjust the icons and links properly.Make sure the color of footer is properly matches with other part of website.

**Comment by Sawan-Kushwah** [comment]
can i work on this

**Comment by Abhay-hack** [comment]
Hi Sawan, I'm assigning this issue to you. For any help just message me.

**Comment by Abhay-hack** [comment]
Hi Sawan you correctly cloned the code. Make sure to install all dependencies

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/b258c28a-4758-46d6-a397-bf554f3ba60d)

i am not able to get the background of this footer design ?

**Comment by Abhay-hack** [comment]
Design is good. Make sure it is fitted properly, then you can send a pull request!

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/102842fd-b4ca-4211-9b4c-5b088e7d2bee)
 @Abhay-hack  i have make as exact as possible could you provide level tag ? 
 if any changes required please let me know
then i will make pr

**Comment by Sawan-Kushwah** [comment]
@Abhay-hack  level tag ? 
for GirlScript Summer Of Code 
then i only i am able to get points 2024 ext

**Comment by Abhay-hack** [comment]
Ok assigning this tag, afterwards you can make a pull request!
