### ISSUE TITLE
Fix: Button Issue

### ISSUE THREAD

**Issue by Abhay-hack** [RCCTechzClub/TechzRevamp#13]
![Button](https://github.com/user-attachments/assets/3b3371bd-0f51-4d5b-92f3-776a054cdcdd)

**Comment by Abhay-hack** [comment]
Fix the button so that it properly align with respect to image.

**Comment by Rihem-taboubi** [comment]
I would like to work on this issue.

**Comment by Abhay-hack** [comment]
Sure, I'm assigning this issue to you :)

**Comment by Abhay-hack** [comment]
Are you working on this issue.
