### ISSUE TITLE
Design "const ourWork = () => { }" Section

### ISSUE THREAD

**Issue by Vaibhav-Samdani** [RCCTechzClub/TechzRevamp#14]
I would like to design a part of the front end code .
I would like to design the proposed "const ourWork = () => { }" section from the front end code .
I am GSSOC contributor and I would like to get this pull request

#Screenshot 
![image](https://github.com/user-attachments/assets/7da89ae1-3fb7-435f-a8fc-5eb419d309d9)

**Comment by Abhay-hack** [comment]
I'm assigning this issue to you. Feel free to contact me for any help :)

**Comment by Vaibhav-Samdani** [comment]
Thank you for assigning this to me.
Please also add gssoc24-ext label.

**Comment by Abhay-hack** [comment]
> Thank you for assigning this to me. Please also add gssoc24-ext label.

Thanks for reminding me about this!

**Comment by Vaibhav-Samdani** [comment]
Can you provide me the drive link of the vector images used in the design for high quality creation?

**Comment by Abhay-hack** [comment]
Okay i will provide you soon :)

**Comment by Vaibhav-Samdani** [comment]
@Abhay-hack  Please provide me the vector images!!

**Comment by Abhay-hack** [comment]
Hi Vaibhav, you can use the given images. I contacted the admin yesterday, but she didn't respond to me back !> @Abhay-hack  Please provide me the vector images!!

**Comment by Abhay-hack** [comment]
Make sure the page must cover whole area!

**Comment by Vaibhav-Samdani** [comment]
can you explain what do you mean by whole area?

**Comment by Abhay-hack** [comment]
Can you tell me what you have redesigned! . It is same

**Comment by Vaibhav-Samdani** [comment]
Design means developed the code for the design. sorry for the miscommunication!

**Comment by Abhay-hack** [comment]
Ok I'm merging your pull request :)
