### ISSUE TITLE
Designing magazine page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RCCTechzClub/TechzRevamp#15]
![image](https://github.com/user-attachments/assets/495ea6b0-0755-42fb-a75e-4383b17c0661)
please assign me this i want to work on this page

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/aac3714d-ea04-4340-9f44-81cfa4216b3f)
See this design if it seems good to you ?
then i will create pull request

**Comment by Abhay-hack** [comment]
You have to make the entire page. Not just the only button.

**Comment by Sawan-Kushwah** [comment]
@Abhay-hack  
entire page means ? can you please explain

**Comment by Abhay-hack** [comment]
This button issue was already there .

**Comment by Abhay-hack** [comment]
Ok you can make a pull request.
