### ISSUE TITLE
Designing Navbar.

### ISSUE THREAD

**Issue by dev129** [RCCTechzClub/TechzRevamp#16]
The Navbar at the top of the page can easily be designed by me, all i need to know is whether the navbar should be sticky or not. Since i have a mastery in next js, tis can easily be done by me.

**Comment by Abhay-hack** [comment]
You can design the sticky navbar!

**Comment by dev129** [comment]
Some more question what should be done for each elemtn on hovering ? The navabr is ready and made sticky 
![navabr](https://github.com/user-attachments/assets/dc1f7eb9-403c-42e5-a530-7a8a0215e8fa)

**Comment by Abhay-hack** [comment]
The anchor tag should change colours and must be spacing between them

**Comment by dev129** [comment]
Okay and which colors shoud login and signup change and what is the distance you want  ? Also i am going to use Link component since its much better and faster

**Comment by Abhay-hack** [comment]
> Okay and which colors shoud login and signup change and what is the distance you want  ? Also i am going to use Link component since its much better and faster , what do you have a say in this ? 
Use space between. Not too much distance.

**Comment by dev129** [comment]
https://github.com/user-attachments/assets/dc3f7fc0-cc1d-4c14-852d-4d447f6e2e61

Hi this shows the working of Navbar, can i raise the PR now?

**Comment by Abhay-hack** [comment]
Yes
