### ISSUE TITLE
Design a responsive footer for a website.

### ISSUE THREAD

**Issue by SurajSakhare100** [RCCTechzClub/TechzRevamp#20]
![Screenshot 2024-10-06 163236](https://github.com/user-attachments/assets/78db6c14-9061-4772-b53b-4526e04619e6)

@Abhay-hack  I like to do this task, please assign it to me under GSSoC and Hacktoberfest ,

**Comment by Abhay-hack** [comment]
This issue already has been solved by other person!

**Comment by SurajSakhare100** [comment]
@Abhay-hack , I think the landing page is complete, but I'd love to continue working with you. If possible, could you assign me another task? It would be really helpful for me.

**Comment by Abhay-hack** [comment]
ok sure !

**Comment by Abhay-hack** [comment]
@SurajSakhare100 Can you make a Faq's page for this website

**Comment by SurajSakhare100** [comment]
@Abhay-hack ya sure !

**Comment by Abhay-hack** [comment]
Checkout Issue #21

**Comment by Abhay-hack** [comment]
> Checkout Issue #21
