### ISSUE TITLE
Feature: Create a Faq's Page 💯 

### ISSUE THREAD

**Issue by Abhay-hack** [RCCTechzClub/TechzRevamp#21]
Create a Faq's Page for this website

**Comment by SurajSakhare100** [comment]
@Abhay-hack assign me this .

**Comment by SurajSakhare100** [comment]
@Abhay-hack Do you have any designs available, or should I search for one?

**Comment by Abhay-hack** [comment]
No you have to search for it !

**Comment by SurajSakhare100** [comment]
![Screenshot 2024-10-06 170125](https://github.com/user-attachments/assets/6c142457-e372-41e4-9295-ba58405efcd3)
@Abhay-hack 
is this okey !

**Comment by Abhay-hack** [comment]
Yeah sure go through it!

**Comment by SurajSakhare100** [comment]
![Screenshot 2024-10-06 175537](https://github.com/user-attachments/assets/1a3d7bd8-e613-4818-a998-d807dd2bc0f8)

is this okey or need any improvement, if no can you please assign this as hactoctoberfest label also ..

**Comment by Abhay-hack** [comment]
Yeah the format is good but you have to apply matching colours and also faqs questions related to the website.

**Comment by SurajSakhare100** [comment]
okey 👍
