### ISSUE TITLE
PROJECT PAGE as we can see in footer and navbar

### ISSUE THREAD

**Issue by Sawan-Kushwah** [RCCTechzClub/TechzRevamp#26]
We have a link to project page but project page design is not there should I made it by my own or you will provide design of it?

**Comment by Abhay-hack** [comment]
I didn't understand are you talking about figma design!

**Comment by Sawan-Kushwah** [comment]
![Screenshot_20241006_195134](https://github.com/user-attachments/assets/d99b2d25-ab3c-4459-b77e-438c456aa455)
As you see in Navbar here we have project


![Screenshot_2024_1006_195152](https://github.com/user-attachments/assets/d7eb475e-3671-4541-80bb-ec2bc9376721)
But in figma there is no design of project page

**Comment by Abhay-hack** [comment]
Oh like you are saying you want to made nav links clickable in figma is it if i'm not wrong !

**Comment by Sawan-Kushwah** [comment]
I want to make project page so as we click on project it should move to that project page

**Comment by Abhay-hack** [comment]
Ok i got it but can i know sample projects as demo you are placing !

**Comment by Abhay-hack** [comment]
Hi Sawan thanks for raising this issue but i found other idea too good i have assigned the issue to him. Thank you!
