### ISSUE TITLE
Add Project Page to Showcase Club Projects and Skills

### ISSUE THREAD

**Issue by SurajSakhare100** [RCCTechzClub/TechzRevamp#27]
Similar to This:

![project page](https://github.com/user-attachments/assets/77524dc4-6171-4cb7-a1d5-2b57b1e741f1)

Description: We need to create a dedicated project page that displays the various projects undertaken by the club along with the skills required for each project. This will help highlight our achievements and the expertise of our members.

@Abhay-hack  I would like to request that the task for adding the project page to showcase our club's projects and skills be assigned to me. I believe this will be a great opportunity for me to contribute under both GSSoC and Hacktoberfest.

**Comment by SurajSakhare100** [comment]
https://github.com/user-attachments/assets/54aef97c-556b-4eb3-a5a9-e39857ac40ca

@Abhay-hack  adding club skills and projects. Let me know if there's any further improvement needed. If everything looks good, can I create a PR? Also, could you assign it the gssoce-ext label with level 2 or 3 please..?

**Comment by Abhay-hack** [comment]
Yeah it's too good. You can make a pr!
